add focus and blur event
openseadragon/openseadragon pull request #2301
Opened 2023-02-19 10:23 UTC by MohitBansal321

**When the user Click on Image Focus Event will work
When the user Click on outside of Image Blur Event will work**

2023-02-19 18:37 UTC, msalsbery commented
This isn't necessarily nor does it capture all the focus and blur possibilities. The DOM events are fine here.

See [my comment here](https://github.com/openseadragon/openseadragon/issues/1657#issuecomment-1436061002)

2023-02-21 22:34 UTC, iangilman requested changes
@MohitBansal321, looking good to me! BTW, you should put in your description that it fixes https://github.com/openseadragon/openseadragon/issues/1657. 

@msalsbery thank you for reviewing this. I think it's looking good now... Do you concur? If not, what needs changing? 

@btzr-io, I know it was years ago that you suggested this, so it's probably not relevant for you anymore, but I'm just curious if this patch looks like it would do what you were hoping for. :)

2023-02-21 22:34 UTC, iangilman commented on src/viewer.js
> +     * Raised when a pointer focus on the {@link OpenSeadragon.Viewer#canvas} element.
I think a better phrasing would be `Raised when the {@link OpenSeadragon.Viewer#canvas} element gets keyboard focus.`

2023-02-21 22:34 UTC, iangilman commented on src/viewer.js
> +     * Raised when a pointer blur on the {@link OpenSeadragon.Viewer#canvas} element.
I think a better phrasing would be `Raised when the {@link OpenSeadragon.Viewer#canvas} element loses keyboard focus.`

2023-02-21 22:39 UTC, msalsbery commented
> 
> 
> @msalsbery thank you for reviewing this. I think it's looking good now... Do you concur? If not, what needs changing? 
> 
> 
>

Aside from the two doc comment changes I requested, it looks good to me!

I like your recommended doc comments phrasing, thank you!

2023-02-21 22:41 UTC, btzr-io commented
> @btzr-io, I know it was years ago that you suggested this, so it's probably not relevant for you anymore, but I'm just curious if this patch looks like it would do what you were hoping for. :)

Yes, this expected behavior:
> When the user Click on Image Focus Event will work
> When the user Click on outside of Image Blur Event will work

2023-02-22 05:50 UTC, msalsbery approved these changes

2023-02-23 23:04 UTC, iangilman approved these changes
@MohitBansal321 Wonderful, thank you for getting the details right!

2023-02-23 23:04 UTC, merged