fixed position issue
openseadragon/openseadragon pull request #2393
Opened 2023-08-15 11:44 UTC by VIRAT9358

#496  fixed
Custom location navigator position is changed from 'fixed' to 'relative' .
Code changes-
if (style.position === 'static') { style.position = 'relative'; }

2023-08-15 16:34 UTC, iangilman requested changes
Apologies... I appear to have led you to the wrong spot! This file doesn't need to change. Instead here's the spot that needs changing: 

https://github.com/openseadragon/openseadragon/blob/17cd6b51ce34fbf3ac3fdcce86851cccb1b12f8b/src/controldock.js#L62

Also, instead of looking at the element's style directly, we should get the computed style (so we pick up any styling that came from CSS style sheets), like so:

```
$.getElementStyle(this.element).position
```

One more thing: the statement needs to be broken up so the `if` and its opening curly bracket are on one line, the assignment is on a second line, and the ending curly bracket is on the third line. Otherwise our linter won't allow it to pass.

Thank you for working on this!

2023-08-16 17:19 UTC, iangilman commented on src/controldock.js
> +            // this.element.style.position = 'relative';
Please delete this... we don't need it commented out here.

2023-08-16 17:25 UTC, iangilman commented on src/navigator.js
> +        style.position = 'relative';
Please update this so it matches the original. As you can see here, you've removed some spaces next to the equals sign.

2023-08-17 05:11 UTC, VIRAT9358 commented
Changes made as mentioned by you .
Regards ,
Virat Srivastava

On Wed, Aug 16, 2023 at 10:55 PM Ian Gilman ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/navigator.js
> <https://github.com/openseadragon/openseadragon/pull/2393#discussion_r1296223582>
> :
>
> > @@ -162,7 +162,7 @@ $.Navigator = function( options ){
>      this.displayRegion.className = 'displayregion';
>
>      (function( style, borderWidth ){
> -        style.position      = 'relative';
> +        style.position = 'relative';
>
> Please update this so it matches the original. As you can see here, you've
> removed some spaces next to the equals sign.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openseadragon/openseadragon/pull/2393#pullrequestreview-1581104702>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARYOHZX2LYNRLHX4TSPL5CLXVT67PANCNFSM6AAAAAA3Q6SY4M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-22 17:16 UTC, iangilman approved these changes
Beautiful! Thank you for solving this issue and taking the time to get it right!

2023-08-22 17:16 UTC, merged